# Generated by Django 3.1.3 on 2021-03-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default='Emad Ahmed', max_length=100),
        ),
    ]
