# Generated by Django 3.1.3 on 2021-03-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
